#! /bin/bash
# BSPWM Launch Script
# This script is run when bspwm starts
# This script if host-aware - so that we only need one script with all settings 
# for every host we run BSWPWM on.

# define the run funtion to check if a program is already running - start it if not

_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

# use input remapper to make desktop switching possible with mouse keys
bash -c "input-remapper-control --command stop-all && input-remapper-control --command autoload"

# Check for external screens if the office monitor is connected - we are most likely runnig docked at the office
# run this every time bspwm is (re)loaded - this variable might come in handy
if xrandr -q | grep '3440x1440'; then
	OFFICE="true"
fi

# disable internal screen if we run docked - but only on the first run - we are using the dock-script to handle 
# docking/undocking at runtime
if [[ "$1" = 0 ]]; then
	if $OFFICE == "true"; then 
		# disabling the internal display
		xrandr --output eDP-1 --off
		# if we are in the office, chances are that we are running the G815 keyboard - fix the rainbow wave...
		g815-led -a 0080ff
	else 
		# the external displays are not present enable the internal one
		xrandr --output eDP-1 --auto
	fi
fi

# let's check on which host we are
HOSTNAME=`cat /etc/hostname`

# set cursor to arrow if no windo is open
xsetroot -cursor_name arrow

# start ssh-agent - but check if it's running first... running multiple ssh-agents will cause all sorts of headaches
if ! pgrep -x "ssh-agent" &>/dev/null; then
        eval "$(ssh-agent)"
fi

# set numlock to always on - this will disable / disregard the numlock key... it's just always ON!
setxkbmap -option numpad:mac

# pull up a wallpaper
#feh --bg-fill /home/daniel/Pictures/Wallpaper/wp4469542-7680x4320-wallpapers.jpg
#feh --bg-fill ~/Pictures/Wallpaper/1213388.jpg
feh --bg-fill ~/Pictures/Wallpaper/autumn-door-1920x1080-v0-n73atvppx1nb1.jpg

# remove unused and unplugged monitors - maybe this needs some work?
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# place desktops on monitors - but only if we are running bspwm for the first time
if [[ "$1" = 0 ]]; then
	# if we are running docked we wan't to display 10 Desktops on the big screen and only one on the side pannel
	if [ $OFFICE == "true" ]; then
		bspc monitor DP-1-2 -d A
		bspc monitor DP-1-3 -d 1 2 3 4 5 6 7 8 9 10
	# if we are not docked we are most likely running without an external display - spawn all desktops on te internal one
	else 
		bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
	fi
fi

# nvidia problems with openGL apps...
#bspc config pointer_motion_interval 10

# set mouse modifier to Alt
bspc config pointer_modifier mod1

# define a small yellow border
bspc config border_width         2

#bspc config focused_border_color "#eabf58"
#bspc config focused_border_color "#F0C674"
bspc config focused_border_color "#4FC3F7"

# define a small gap between windows
bspc config window_gap          5

# use mouse following focus mode
bspc config focus_follows_pointer true

# split the tiles 50-50 by default
bspc config split_ratio          0.5

# autoload programs which will be used all the time...
# start pcloud

_run pcloud

# start insync
_run insync start

# launch networkmanager applet
#_run nm-applet 

# start flameshot
flatpak run org.flameshot.Flameshot &

# launch screensaver - to display pictures and to be able to lock the screen
_run xscreensaver --no-splash

# launch compositor with custom settings. 
_run picom --config /home/daniel/.config/picom/picom.conf --experimental-backends -b &

# launch touchegg. 
_run touchegg

# launch notification-helper 
_run dunst

# launch polkit-agent . 
_run lxpolkit

# lauch keyboard shortcut deamon. kill it if it's already up
_run sxhkd

# launch polybar. kill it if it's already up
_run ~/.config/polybar/launch.sh --shapes

# run NetworkManager Applet - we still need it to change wired profiles
_run nm-applet


# some defaults that may come in handy later
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off